import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const apiSlice = createApi({
  reducerPath: "api",
  tagTypes: ["api"],
  baseQuery: fetchBaseQuery({
    baseUrl: "https://fakestoreapi.com/",
    prepareHeaders: (headers) => {
      headers.set("Content-type", "application/json");
      return headers;
    },
  }),
  endpoints: () => ({}),
});

export default apiSlice;
// Generated by https://quicktype.io
